### ISSUE TITLE
Maybe doesn't work

### ISSUE THREAD

**Issue by xbony2** [xbony2/Bonemealable-babies#2]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.12-1.5.2.jar)
  CTMCorePlugin (CTM-MC1.12-0.1.1.2.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  ForgeGroovePlugin (forgegroove-1.0.0a.jar)
  AstralCore (astralsorcery-1.5.8.jar)
  AppleCore (AppleCore-mc1.12-2.2.1.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63+dev.98.jar)
  LoadingPlugin (Quark-r1.2-99.jar)
  BlurPlugin (Blur-1.0.3-13.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 7/7/17 9:52 PM
Description: Unexpected error

groovy.lang.MissingPropertyException: No such property: isRemote for class: net.minecraft.client.multiplayer.WorldClient
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at xbony2.bonemealablebabies.BonemealableBabies$BoneMealHandler.boneMealAnimals(BonemealableBabies.groovy:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_316_BoneMealHandler_boneMealAnimals_EntityInteractSpecific.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onInteractEntityAt(ForgeHooks.java:1057)
	at net.minecraftforge.common.ForgeHooks.onInteractEntityAt(ForgeHooks.java:1051)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187102_a(PlayerControllerMP.java:552)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1560)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2248)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2014)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1801)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at xbony2.bonemealablebabies.BonemealableBabies$BoneMealHandler.boneMealAnimals(BonemealableBabies.groovy:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_316_BoneMealHandler_boneMealAnimals_EntityInteractSpecific.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.common.ForgeHooks.onInteractEntityAt(ForgeHooks.java:1057)
	at net.minecraftforge.common.ForgeHooks.onInteractEntityAt(ForgeHooks.java:1051)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187102_a(PlayerControllerMP.java:552)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1560)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2248)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2014)
```

Which is strange, it seems to work alright in my dev environment.

~Maybe changing it to getWorld()."isRemote" would work, but I dunno I'm too tired to test all of that now.~ lol no escaping it doesn't help

**Comment by xbony2** [comment]
It doesn't crash anymore! Doesn't work however:
```
java.util.concurrent.ExecutionException: groovy.lang.MissingMethodException: No signature of method: net.minecraft.item.ItemStack.getItem() is applicable for argument types: () values: []
Possible solutions: getAt(java.lang.String), getClass(), grep()
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chb.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: groovy.lang.MissingMethodException: No signature of method: net.minecraft.item.ItemStack.getItem() is applicable for argument types: () values: []
Possible solutions: getAt(java.lang.String), getClass(), grep()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58) ~[ScriptBytecodeAdapter.class:?]
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49) ~[PojoMetaClassSite.class:?]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[CallSiteArray.class:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[AbstractCallSite.class:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117) ~[AbstractCallSite.class:?]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:80) ~[AbstractCallSite.class:?]
	at xbony2.bonemealablebabies.BonemealableBabies$BoneMealHandler.boneMealAnimals(BonemealableBabies.groovy:26) ~[BonemealableBabies$BoneMealHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_316_BoneMealHandler_boneMealAnimals_EntityInteractSpecific.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onInteractEntityAt(ForgeHooks.java:1057) ~[ForgeHooks.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1066) ~[oy.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
	at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

**Comment by xbony2** [comment]
No longer trying to use Groovy, so this is not relevant.
